default_set: 'two-ubuntu-server-12042-x64'
sets:
  'two-ubuntu-server-12042-x64':
    default_node: 'first.vm'
    nodes:
      'first.vm':
        prefab: 'ubuntu-server-12042-x64'
        options:
                 ip: '10.11.12.2'
      'second.vm':
        prefab: 'ubuntu-server-12042-x64'
        options:
                 ip: '10.11.12.3'
  'one-ubuntu-server-12042-x64':
    nodes:
      'first.vm':
        prefab: 'ubuntu-server-12042-x64'
